---
- name: "Install sudo"
  ansible.builtin.package:
    pkg: "sudo"
    state: present

- name: Add deploy user
  ansible.builtin.user:
    name: "{{ harden_linux_deploy_user }}"
    password: "{{ harden_linux_deploy_user_password }}"
    uid: "{{ harden_linux_deploy_user_uid }}"
    shell: "{{ harden_linux_deploy_user_shell }}"
    home: "{{ harden_linux_deploy_user_home }}"
  tags:
    - user

- name: Add authorized keys for deploy user
  ansible.builtin.authorized_key:
    user: "{{ harden_linux_deploy_user }}"
    key: "{{ lookup('file', item) }}"
  loop: "{{ harden_linux_deploy_user_public_keys }}"
  when: harden_linux_deploy_user_public_keys is defined
  tags:
    - user

- name: "Ensure deploy user present in /etc/sudoers.d/{{ harden_linux_deploy_user }}"
  ansible.builtin.template:
    src: "etc/sudoers.d/deployuser.j2"
    dest: "/etc/sudoers.d/{{ harden_linux_deploy_user }}"
    owner: "root"
    group: "root"
    mode: "0400"
  tags:
    - user
    - sudo

- name: Ensure deploy user is absent in /etc/sudoers
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers"
    regexp: "^{{ harden_linux_deploy_user }} ALL"
    state: absent
  tags:
    - user
    - sudo
