---
- name: "Install sudo"
  package:
    pkg: "sudo"
    state: present

- name: Add deploy user
  user:
    name: "{{ harden_linux_deploy_user }}"
    password: "{{ harden_linux_deploy_user_password }}"
    uid: "{{ harden_linux_deploy_user_uid }}"
    shell: "{{ harden_linux_deploy_user_shell }}"
    home: "{{ harden_linux_deploy_user_home }}"
  tags:
    - user

- name: Add authorized keys for deploy user
  authorized_key:
    user: "{{ harden_linux_deploy_user }}"
    key: "{{ lookup('file', item) }}"
  loop: "{{ harden_linux_deploy_user_public_keys }}"
  when: harden_linux_deploy_user_public_keys is defined
  tags:
    - user

- name: Add deploy user to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ harden_linux_deploy_user }} ALL"
    line: "{{ harden_linux_deploy_user }} ALL=(ALL) NOPASSWD:ALL"
    state: present
  tags:
    - user
    - sudo
