---
- name: Update sshguard whitelist file
  ansible.builtin.lineinfile:
    dest: "{{ harden_linux_sshguard_whitelist_file }}"
    regexp: "^{{ whitelist_entry }}"
    line: "{{ whitelist_entry }}"
    state: present
  loop: "{{ harden_linux_sshguard_whitelist }}"
  loop_control:
    loop_var: whitelist_entry
  notify:
    - Restart sshguard
  tags:
    - sshguard
