---
- name: Update sshguard whitelist file
  lineinfile:
    dest: "{{ harden_linux_sshguard_whitelist_file }}"
    regexp: "^{{ whitelist_entry }}"
    line: "{{ whitelist_entry }}"
    state: present
  with_items:
    - "{{ harden_linux_sshguard_whitelist }}"
  loop_control:
    loop_var: whitelist_entry
  notify:
    - restart sshguard
  tags:
    - sshguard
