---
- name: reload ufw
  ufw:
    state: reloaded

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart ntpd
  service:
    name: "{{ harden_linux_ntp }}"
    state: restarted

- name: restart systemd-timesyncd
  service:
    name: systemd-timesyncd
    state: restarted

- name: restart sshguard
  service:
    name: sshguard
    state: restarted
