---
- name: reload ufw
  ansible.builtin.ufw:
    state: reloaded

- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: "{{ item }}"
  loop:
    - stopped
    - started
  when:
    - not ansible_distribution|lower == 'archlinux'
  listen: "restart ssh"

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: "{{ item }}"
  loop:
    - stopped
    - started
  when:
    - ansible_distribution|lower == 'archlinux'
  listen: "restart ssh"

- name: restart ntpd
  ansible.builtin.service:
    name: "{{ harden_linux_ntp }}"
    state: restarted

- name: restart systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: restart sshguard
  ansible.builtin.service:
    name: sshguard
    state: restarted
