---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 192
      cpus: 2

platforms:
  - name: test-harden-linux-ubuntu2004-timesyncd
    box: generic/ubuntu2004
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.10
  - name: test-harden-linux-ubuntu2004-ntp
    box: generic/ubuntu2004
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.20
  - name: test-harden-linux-ubuntu1804-openntpd
    box: generic/ubuntu1804
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.30
  - name: test-harden-linux-arch-timesyncd
    box: archlinux/archlinux
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.40
  - name: test-harden-linux-ubuntu2204-timesyncd
    box: alvistack/ubuntu-22.04
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.50

role_name_check: 1

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        harden_linux_root_password: "{{ lookup('file', 'myuserpassword_hash') }}" # mypassword
        harden_linux_deploy_user: deployer
        harden_linux_deploy_user_password: "{{ lookup('file', 'myuserpassword_hash') }}" # mypassword
        harden_linux_deploy_user_home: /home/deployer
        harden_linux_deploy_user_public_keys:
          - "mykey.pub"
        harden_linux_sshd_settings:
          "^PasswordAuthentication": "PasswordAuthentication yes"
          "^X11Forwarding": "X11Forwarding no"
        harden_linux_sysctl_settings_user:
          "net.ipv4.ip_forward": 1
          "net.ipv6.conf.default.forwarding": 1
          "net.ipv6.conf.all.forwarding": 1
        harden_linux_ufw_allow_networks:
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"
        harden_linux_ufw_logging: 'on'
        harden_linux_ufw_defaults_user:
          "^DEFAULT_FORWARD_POLICY": 'DEFAULT_FORWARD_POLICY="ACCEPT"'
        harden_linux_ufw_rules:
          - rule: "allow"
            to_port: "22"
            protocol: "tcp"
          - rule: "allow"
            to_port: "80"
            protocol: "tcp"
          - rule: "allow"
            to_port: "443"
            protocol: "tcp"
        harden_linux_sshguard_whitelist:
          - "127.0.0.0/8"
          - "::1/128"
          - "10.0.0.0/8"
    host_vars:
      test-harden-linux-ubuntu2004-timesyncd:
        harden_linux_ntp: "systemd-timesyncd"
        harden_linux_ntp_settings:
          "^#NTP=": "NTP=ntp.ubuntu.com"
        harden_linux_optional_packages:
          - mlocate
      test-harden-linux-ubuntu2004-ntp:
        harden_linux_ntp: "ntp"
        harden_linux_ntp_settings:
          "^pool 0": "pool 0.ubuntu.pool.ntp.org iburst"
          "^pool 1": "pool 1.ubuntu.pool.ntp.org iburst"
          "^pool 2": "pool 2.ubuntu.pool.ntp.org iburst"
          "^pool 3": "pool 3.ubuntu.pool.ntp.org iburst"
      test-harden-linux-ubuntu1804-openntpd:
        harden_linux_ntp: "openntpd"
        harden_linux_ntp_settings:
          "^servers 0": "servers 0.debian.pool.ntp.org"
          "^servers 1": "servers 1.debian.pool.ntp.org"
          "^servers 2": "servers 2.debian.pool.ntp.org"
          "^servers 3": "servers 3.debian.pool.ntp.org"
      test-harden-linux-arch-timesyncd:
        harden_linux_ntp: "systemd-timesyncd"
        harden_linux_optional_packages:
          - mlocate
      test-harden-linux-ubuntu2204-timesyncd:
        harden_linux_ntp: "systemd-timesyncd"
        harden_linux_ntp_settings:
          "^#NTP=": "NTP=ntp.ubuntu.com"
        harden_linux_optional_packages:
          - mlocate

scenario:
  name: kvm
  test_sequence:
    - prepare
    - converge

verifier:
  name: testinfra
  directory: tests
  options:
    # Add a -v so you see the individual test names,
    # particularly useful with parameterized tests
    v: true
    sudo: true
  lint:
    name: flake8
